import path from 'node:path';
import {readFile,writeFile,mkdir,copyFile,stat} from 'node:fs/promises';
import JSZip from 'jszip';
import validator from 'gltf-validator';
import {inspectImage} from './images.mjs';
import sharp from 'sharp';
import {createRenderer} from './renderer.mjs';
import {performance} from 'node:perf_hooks';
import {VERSION,uid,inside,safeName,fileHash,saveJson,escapeHtml as esc} from './util.mjs';
import {makeRecipe,makePolicy,epoch,persist} from './project.mjs';
async function embedded(file){try{const b=await readFile(file);return `data:image/png;base64,${b.toString('base64')}`;}catch{return '';}}
function publicMetrics(value){if(Array.isArray(value))return value.map(publicMetrics);if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).filter(([k])=>!['path','file','sourcePath','outputDir','workDir'].includes(k)).map(([k,v])=>[k,publicMetrics(v)]));if(typeof value==='string'){if(path.isAbsolute(value))return path.basename(value);return value.replace(/(?:\/Users\/|\/home\/|\/private\/|\/tmp\/)[^\s\"']+/g,'[managed path]');}return value;}
export async function exportDelivery(dir,p,budgetName){
 dir=path.resolve(dir);
 const allocation=p.allocations[budgetName];if(!allocation?.feasible)throw new Error('No feasible allocation to export');
 if(p.assets.some(a=>a.epoch!==epoch(a,p)))throw new Error('Candidate archive is stale; regenerate before export');
 const exportId=`${safeName(budgetName)}-${uid()}`,out=path.join(dir,'exports',exportId);await mkdir(path.join(out,'assets'),{recursive:true});
 const manifest={schemaVersion:1,version:VERSION,projectName:p.name,budgetName,budgetBytes:p.budgets.find(b=>b.name===budgetName).bytes,assetBytes:0,definition:'Sum of the actual bytes of the selected visual asset files. 1 MB = 1,000,000 bytes; 1 MiB = 1,048,576 bytes. Metadata and ZIP bytes are separate.',assets:[]};
 const report={schemaVersion:1,createdAt:new Date().toISOString(),allocation,scoreDefinition:'Priority-weighted mean of reference-anchored RGBA and edge differences in declared 2D usage conditions. An engineering proxy, not perceptual retention or aesthetics.',scope:allocation.exact?'Exact allocation over measured valid candidate table at current weights. All candidate versions are retained; no claim of globally optimal encoding.':allocation.scope,cost:p.cost,environment:p.environment,settings:p.settings,assets:[]};
 const sections=[];
 for(const a of p.assets){const c=a.candidates.find(c=>c.id===allocation.selected[a.id]);if(!c?.valid)throw new Error('Selected candidate is not valid');if(a.type==='glb'&&!c.finalCheck){const start=performance.now(),renderer=await createRenderer({workDir:path.join(dir,'export-renders')});try{const ref=await renderer.reference(inside(dir,a.source),a.usages);const check=await renderer.evaluate(inside(dir,c.file),ref,{heldout:true});const normalize=v=>Array.isArray(v)?v.map(normalize):v&&typeof v==='object'?Object.fromEntries(Object.entries(v).map(([k,x])=>[k,normalize(x)])):typeof v==='string'&&v.startsWith(dir+path.sep)?path.relative(dir,v):v;c.finalCheck=normalize(check);}finally{await renderer.close();const ms=performance.now()-start;p.cost.exportCheckMs=(p.cost.exportCheckMs??0)+ms;p.cost.elapsedMs+=ms;}}if(c.finalCheck?.valid===false)throw new Error('Selected GLB failed separate post-selection render checks');const source=inside(dir,c.file);if(await fileHash(source)!==c.hash||(await stat(source)).size!==c.bytes)throw new Error('Candidate changed on disk; export stopped');
 if(!(/^[a-zA-Z0-9-]+$/).test(a.id))throw new Error('Invalid asset ID');
 const dest=`assets/${a.id}-${safeName(path.parse(a.name).name)}${path.extname(c.file)}`;await copyFile(source,inside(out,dest));manifest.assetBytes+=c.bytes;
 manifest.assets.push({id:a.id,name:a.name,type:a.type,file:dest,bytes:c.bytes,sha256:c.hash,sourceSha256:a.sourceHash,candidateId:c.id,usages:a.usages});
 const next=a.candidates.filter(v=>v.valid&&v.bytes>c.bytes&&v.metrics.loss<c.metrics.loss).sort((x,y)=>x.bytes-y.bytes)[0];
 const entry={id:a.id,name:a.name,type:a.type,license:a.license,sourceBytes:a.sourceBytes,usages:a.usages,constraints:a.constraints,priority:a.priority,selected:publicMetrics(c),nextUpgrade:next?{id:next.id,bytes:next.bytes,extraBytes:next.bytes-c.bytes,lossReduction:c.metrics.loss-next.metrics.loss}:null,candidates:a.candidates.map(publicMetrics),observations:publicMetrics(a.observations??[])};report.assets.push(entry);
 const preview=c.metrics?.preview??c.preview;const original=a.candidates.find(v=>v.id==='original');const previewPath=typeof preview==='string'?preview:preview?.candidate;const originalPath=c.metrics?.reference??original?.metrics?.preview??original?.preview;
 const src=previewPath?await embedded(inside(dir,previewPath)):a.type==='image'?`data:image/${path.extname(c.file).slice(1)};base64,${(await readFile(source)).toString('base64')}`:'';
 const orig=typeof originalPath==='string'?await embedded(inside(dir,originalPath)):a.type==='image'?`data:image/${path.extname(a.source).slice(1)};base64,${(await readFile(inside(dir,a.source))).toString('base64')}`:'';
 const diff=c.metrics?.difference?await embedded(inside(dir,c.metrics.difference)):'';
 sections.push(`<section><h2>${esc(a.name)}</h2><p>${a.sourceBytes.toLocaleString()} → ${c.bytes.toLocaleString()} asset bytes · priority ${a.priority} · proxy loss ${c.metrics.loss.toFixed(6)}</p><div class="pair">${orig?`<figure><img src="${orig}"><figcaption>Original reference</figcaption></figure>`:''}${src?`<figure><img src="${src}"><figcaption>Selected output</figcaption></figure>`:''}${diff?`<figure><img src="${diff}"><figcaption>4× amplified difference at declared display size</figcaption></figure>`:''}</div><p>${next?`Next measured upgrade: ${next.bytes-c.bytes} extra bytes; proxy loss decrease ${(c.metrics.loss-next.metrics.loss).toFixed(6)}.`:'No larger candidate with a lower measured loss in this archive.'}</p><details><summary>Usage, protection, candidate measurements</summary><pre>${esc(JSON.stringify(entry,null,2))}</pre></details></section>`);
 }
 if(manifest.assetBytes>manifest.budgetBytes||manifest.assetBytes!==allocation.bytes)throw new Error('Actual delivery byte verification failed');
 await saveJson(path.join(out,'manifest.json'),manifest);await saveJson(path.join(out,'recipe.json'),makeRecipe(p));await saveJson(path.join(out,'policy.json'),makePolicy(p));await saveJson(path.join(out,'report.json'),report);
 await writeFile(path.join(out,'report.html'),`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>AssetFit — ${esc(p.name)}</title><style>body{font:16px/1.6 system-ui;background:#10151b;color:#e9eef4;max-width:1100px;margin:40px auto;padding:24px}h1{font-size:36px}section{border-top:1px solid #455160;padding:24px 0}.pair{display:flex;gap:24px;flex-wrap:wrap}figure{margin:0;flex:1 1 250px;min-width:0;max-width:100%}img{max-width:100%;max-height:400px;object-fit:contain;background:#26313b}pre{white-space:pre-wrap;overflow-wrap:anywhere;font-size:13px}summary{cursor:pointer}</style><h1>AssetFit delivery report</h1><p>${esc(p.name)} / ${esc(budgetName)}</p><p><b>${manifest.assetBytes.toLocaleString()} / ${manifest.budgetBytes.toLocaleString()} asset bytes</b></p><p>${esc(manifest.definition)}</p><p>${esc(report.scoreDefinition)}</p><p>${esc(report.scope)}</p>${sections.join('')}<section><h2>Processing cost and limits</h2><pre>${esc(JSON.stringify(p.cost,null,2))}</pre><p>Held-out rendering, when present, is a separate post-selection check. Search observations do not establish safety at arbitrary angles or lighting. Normal/ORM and protected texture resources are preserved. Exact text or atlas requirements require explicit whole-image constraints.</p></section></html>`);
 const licenseAssets=p.assets.filter(a=>a.license);const extraMetadata=[];if(licenseAssets.length){await saveJson(path.join(out,'SOURCE-LICENSES.json'),{assets:licenseAssets.map(a=>({...a.license,...(a.licenseText?{licenseFile:'licenses/'+safeName(path.basename(a.license.licenseFile))}:{})}))});extraMetadata.push('SOURCE-LICENSES.json');for(const a of licenseAssets.filter(a=>a.licenseText)){const name='licenses/'+safeName(path.basename(a.license.licenseFile));await mkdir(path.join(out,'licenses'),{recursive:true});await writeFile(path.join(out,name),a.licenseText);if(!extraMetadata.includes(name))extraMetadata.push(name);}}
 const verified=await verifyDelivery(out);if(!verified.valid)throw new Error(`Delivery verification failed: ${JSON.stringify(verified.errors)}`);
 const zip=new JSZip();for(const a of manifest.assets)zip.file(a.file,await readFile(path.join(out,a.file)));let metadataBytes=0;for(const name of ['manifest.json','recipe.json','policy.json','report.json','report.html',...extraMetadata]){const b=await readFile(path.join(out,name));zip.file(name,b);metadataBytes+=b.length;}
 const zipped=await zip.generateAsync({type:'nodebuffer',compression:'DEFLATE',compressionOptions:{level:6}});await writeFile(path.join(out,'delivery.zip'),zipped);
 const info={exportId,budgetName,assetBytes:manifest.assetBytes,metadataBytes,zipBytes:zipped.length,verified,files:manifest.assets,archive:`exports/${exportId}/delivery.zip`,report:`exports/${exportId}/report.html`};await saveJson(path.join(out,'delivery-info.json'),info);p.exports??=[];p.exports.push(info);await persist(dir,p);return info;
}
export async function verifyDelivery(dir){const errors=[],manifest=JSON.parse(await readFile(path.join(dir,'manifest.json'),'utf8'));let bytes=0;const seen=new Set();for(const a of manifest.assets){try{if(!['image','glb'].includes(a.type))throw new Error('Unknown asset type in manifest');if(seen.has(a.file))throw new Error('Repeated delivery path');seen.add(a.file);const f=inside(dir,a.file),data=await readFile(f);bytes+=data.length;if(data.length!==a.bytes||await fileHash(f)!==a.sha256)throw new Error('Size/hash mismatch');if(a.type==='image'){await inspectImage(f);await sharp(data,{failOn:'error'}).raw().toBuffer();}if(a.type==='glb'){const v=await validator.validateBytes(new Uint8Array(data),{maxIssues:100});if(v.issues.numErrors)throw new Error(`${v.issues.numErrors} glTF validation errors`);}}catch(e){errors.push({assetId:a.id,error:e.message});}}
 if(bytes!==manifest.assetBytes)errors.push({error:'Asset byte sum differs from manifest'});if(!Number.isSafeInteger(manifest.budgetBytes)||bytes>manifest.budgetBytes)errors.push({error:'Budget exceeded or invalid'});return {valid:errors.length===0,assetBytes:bytes,budgetBytes:manifest.budgetBytes,errors};}
